### ISSUE TITLE
关于内存的问题 求指教

### ISSUE THREAD

**Issue by lahala** [AllLuckly/LBLaunchImageAd#4]
此框架很好，简单易懂，可是发现一个问题：此demo在6plus真机上跑，运行此启动控件的话 内存大约为18M左右，然后不运行此启动控件的话 内存大约为4左右，这无缘无故多了十几M的内存，不知哪里出来的，看了你的代码有做removeFromSuperview释放,而且delloc方法也执行了，始终释放不掉这多余的十几M内存，求指教，详情请看我录的文件
[未命名.mov.zip](https://github.com/AllLuckly/LBLaunchImageAd/files/458875/mov.zip)

**Comment by AllLuckly** [comment]
看了你说的情况，这是正常的，不加载任何 控件的情况 和加载控件的情况 内存大小肯定是不一样的，我试了下 模拟器  启动的时候是79左右 加载完降到了40左右，说明该功能是已经被释放了的

**Comment by lahala** [comment]
模拟器 效果会好点  真机却就会增加 十几M内存  一个view控件 也不会增加 十几M啊   我觉得不正常啊 ，我的项目和你的demo我都是跑的真机  就是增加了十几M  很烦恼

**Comment by AllLuckly** [comment]
试下最新的代码，早晨我推上去的， 我用真机测了下，最多增加5M 左右
![2016-09-08 10 45 35](https://cloud.githubusercontent.com/assets/10387295/18335369/713494f2-75b1-11e6-85c3-64d83b143def.png)
![2016-09-08 10 45 44](https://cloud.githubusercontent.com/assets/10387295/18335370/71f34992-75b1-11e6-972e-e808ab6ca9f1.png)

**Comment by lahala** [comment]
恩恩 刚测试了下 其他类似的框架 都是增加了 一些内存 看来实属正常现象  ，thankS

**Comment by lahala** [comment]
赞👍！！

**Comment by lahala** [comment]
项目就用你这个框架啦 感谢！！已star
