### ISSUE TITLE
最新版的有个问题

### ISSUE THREAD

**Issue by myDonghao** [AllLuckly/LBLaunchImageAd#9]
我看最新版 ： 优化无法释放的问题  重新创建了一个控制器，并设置成了window的rootvc。但是这样一来，就会把我的原本跟控制器给替换掉。导致广告消失之后会显示空白页面...

**Comment by AllLuckly** [comment]
广告消失之后再设置回你自己的rootvc即可

**Comment by myDonghao** [comment]
ok
